"""nova revisão

Revision ID: 4ea44e3c00b7
Revises: ad365d2d7ca2
Create Date: 2025-10-18 19:14:16.605588

"""
from alembic import op
import sqlalchemy as sa

revision = '4ea44e3c00b7'
down_revision = 'ad365d2d7ca2'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tenant_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###