"""nova revisão

Revision ID: 84044a28f995
Revises: 4ea44e3c00b7
Create Date: 2025-10-18 19:21:35.045853

"""
from alembic import op
import sqlalchemy as sa

revision = '84044a28f995'
down_revision = '4ea44e3c00b7'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###