"""init schema

Revision ID: ad365d2d7ca2
Revises: 
Create Date: 2025-10-18 19:09:49.988006

"""
from alembic import op
import sqlalchemy as sa

revision = 'ad365d2d7ca2'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('user', 'image_src',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'image_src',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###